"""add is_private to user

Revision ID: 3fa938410b83
Revises: b4932274842f
Create Date: 2026-05-24 19:01:52.989158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3fa938410b83'
down_revision: Union[str, None] = 'b4932274842f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminauditlog',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adminauditlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adminauditlog_admin_id'), ['admin_id'], unique=False)

    op.drop_table('spatial_ref_sys')
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('group_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('group_icon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('group_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('max_members', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('join_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.alter_column('participant_one_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('participant_two_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_system_message', sa.Boolean(), nullable=False))
        batch_op.alter_column('receiver_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superadmin', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_private')
        batch_op.drop_column('is_superadmin')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('receiver_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('is_system_message')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('participant_two_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('participant_one_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('join_mode')
        batch_op.drop_column('max_members')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('group_description')
        batch_op.drop_column('group_icon_url')
        batch_op.drop_column('group_name')
        batch_op.drop_column('chat_type')

    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    with op.batch_alter_table('adminauditlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adminauditlog_admin_id'))

    op.drop_table('adminauditlog')
    # ### end Alembic commands ###
