"""initial_migration_uuid7

Revision ID: 5626a9bdddb6
Revises: 
Create Date: 2026-03-19 21:49:51.152353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5626a9bdddb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipinfocache',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('loc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('org', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ipinfocache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ipinfocache_ip'), ['ip'], unique=True)

    op.create_table('otp',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('otp_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_phone_number'), ['phone_number'], unique=False)

    op.create_table('user',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_pic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum'), nullable=True),
    sa.Column('is_loop_enabled', sa.Boolean(), nullable=False),
    sa.Column('suspended_until', sa.DateTime(), nullable=True),
    sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('truecaller_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('facebook_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('backup_codes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facebook_id'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('truecaller_id')
    )
    op.create_table('block',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blocker_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blocked_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmarkfolder',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_video_call', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_from'], ['user.id'], ),
    sa.ForeignKeyConstraint(['call_to'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_for_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('participant_one_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('participant_two_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_message_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_one_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['participant_two_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_num', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_owner_id', 'normalized_number', name='uq_contact_owner_number')
    )
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_normalized_number'), ['normalized_number'], unique=False)

    op.create_table('fcmtoken',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('follow',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('follower_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('following_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loginactivity',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('login_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loopprofile',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('displayname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_pic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('suspended_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('memetemplates',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'STICKER', name='templatetype'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('urls', sa.Text(), nullable=False),
    sa.Column('hash_tags', sa.JSON(), nullable=False),
    sa.Column('metadata_info', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notification_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notification_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('redirect_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('redirect_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('redirect_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_pushed', sa.Boolean(), nullable=False),
    sa.Column('push_sent_at', sa.DateTime(), nullable=True),
    sa.Column('push_failed', sa.Boolean(), nullable=False),
    sa.Column('push_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('group_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aggregated_count', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('idx_notification_recipient_category_created', ['recipient_id', 'notification_category', 'created_at'], unique=False)
        batch_op.create_index('idx_notification_recipient_read_created', ['recipient_id', 'is_read', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_group_key'), ['group_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_is_pushed'), ['is_pushed'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_notification_category'), ['notification_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_sender_id'), ['sender_id'], unique=False)

    op.create_table('notificationpreference',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('messages_enabled', sa.Boolean(), nullable=False),
    sa.Column('calls_enabled', sa.Boolean(), nullable=False),
    sa.Column('missed_calls_enabled', sa.Boolean(), nullable=False),
    sa.Column('posts_enabled', sa.Boolean(), nullable=False),
    sa.Column('likes_enabled', sa.Boolean(), nullable=False),
    sa.Column('comments_enabled', sa.Boolean(), nullable=False),
    sa.Column('comment_replies_enabled', sa.Boolean(), nullable=False),
    sa.Column('stories_enabled', sa.Boolean(), nullable=False),
    sa.Column('followers_enabled', sa.Boolean(), nullable=False),
    sa.Column('loop_friend_requests_enabled', sa.Boolean(), nullable=False),
    sa.Column('loop_messages_enabled', sa.Boolean(), nullable=False),
    sa.Column('loop_matches_enabled', sa.Boolean(), nullable=False),
    sa.Column('account_security_enabled', sa.Boolean(), nullable=False),
    sa.Column('login_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('account_status_enabled', sa.Boolean(), nullable=False),
    sa.Column('reports_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quiet_hours_end', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificationpreference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificationpreference_user_id'), ['user_id'], unique=True)

    op.create_table('post',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('posted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['posted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reporter_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sa.Enum('user', 'post', 'comment', 'loop_profile', 'loop_message', name='reporttarget'), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reported_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason', sa.Enum('spam', 'impersonation', 'hate', 'harassment', 'sexual', 'self_harm', 'violence', 'misinformation', 'illegal', 'other', name='reportreason'), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attachments', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('open', 'under_review', 'action_taken', 'dismissed', name='reportstatus'), nullable=False),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reported_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_on', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userdevice',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('last_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userpasskey',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credential_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('userpasskey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userpasskey_credential_id'), ['credential_id'], unique=False)

    op.create_table('usersession',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usersession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usersession_session_token'), ['session_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_usersession_user_id'), ['user_id'], unique=False)

    op.create_table('bookmark',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bookmark_folder_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bookmark_folder_id'], ['bookmarkfolder.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatmute',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('muted_at', sa.DateTime(), nullable=False),
    sa.Column('muted_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatmute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatmute_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatmute_user_id'), ['user_id'], unique=False)

    op.create_table('comment',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reply_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['reply_to'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loopchat',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile1_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile2_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['profile1_id'], ['loopprofile.id'], ),
    sa.ForeignKeyConstraint(['profile2_id'], ['loopprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loopfriend',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('loop_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('friend_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['friend_profile_id'], ['loopprofile.id'], ),
    sa.ForeignKeyConstraint(['loop_profile_id'], ['loopprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loopprofilephoto',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('loop_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['loop_profile_id'], ['loopprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loopprofilephoto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loopprofilephoto_loop_profile_id'), ['loop_profile_id'], unique=False)

    op.create_table('looprequest',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requester_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('receiver_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='looprequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_profile_id'], ['loopprofile.id'], ),
    sa.ForeignKeyConstraint(['requester_profile_id'], ['loopprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'FILE', 'AUDIO', 'POST', 'CALL', 'OTHER', name='messagetype'), nullable=False),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('link_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('media_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('media_thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('media_encryption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_video_call', sa.Boolean(), nullable=True),
    sa.Column('call_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shared_post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_for_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'READ', 'FAILED', name='messagestatus'), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('is_forwarded', sa.Boolean(), nullable=False),
    sa.Column('forwarded_from_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sender_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('receiver_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reply_to_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['forwarded_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shared_post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moderationaction',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('moderator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_meta', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('randomsession',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connected_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connected_profile_id'], ['loopprofile.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['loopprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storymedia',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('story_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('media_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storyview',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('story_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('viewer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loopmessage',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'AUDIO', name='loopmessagetype'), nullable=False),
    sa.Column('media_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_for_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['loopchat.id'], ),
    sa.ForeignKeyConstraint(['sender_profile_id'], ['loopprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reaction',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loopreaction',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['loopmessage.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['loopprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loopreaction')
    op.drop_table('reaction')
    op.drop_table('loopmessage')
    op.drop_table('storyview')
    op.drop_table('storymedia')
    op.drop_table('randomsession')
    op.drop_table('moderationaction')
    op.drop_table('message')
    op.drop_table('media')
    op.drop_table('looprequest')
    with op.batch_alter_table('loopprofilephoto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loopprofilephoto_loop_profile_id'))

    op.drop_table('loopprofilephoto')
    op.drop_table('loopfriend')
    op.drop_table('loopchat')
    op.drop_table('like')
    op.drop_table('comment')
    with op.batch_alter_table('chatmute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatmute_user_id'))
        batch_op.drop_index(batch_op.f('ix_chatmute_chat_id'))

    op.drop_table('chatmute')
    op.drop_table('bookmark')
    with op.batch_alter_table('usersession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usersession_user_id'))
        batch_op.drop_index(batch_op.f('ix_usersession_session_token'))

    op.drop_table('usersession')
    with op.batch_alter_table('userpasskey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userpasskey_credential_id'))

    op.drop_table('userpasskey')
    op.drop_table('userdevice')
    op.drop_table('story')
    op.drop_table('report')
    op.drop_table('post')
    with op.batch_alter_table('notificationpreference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificationpreference_user_id'))

    op.drop_table('notificationpreference')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_sender_id'))
        batch_op.drop_index(batch_op.f('ix_notification_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notification_priority'))
        batch_op.drop_index(batch_op.f('ix_notification_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notification_notification_category'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_notification_is_pushed'))
        batch_op.drop_index(batch_op.f('ix_notification_group_key'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))
        batch_op.drop_index('idx_notification_recipient_read_created')
        batch_op.drop_index('idx_notification_recipient_category_created')

    op.drop_table('notification')
    op.drop_table('memetemplates')
    op.drop_table('loopprofile')
    op.drop_table('loginactivity')
    op.drop_table('follow')
    op.drop_table('fcmtoken')
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_normalized_number'))

    op.drop_table('contact')
    op.drop_table('chat')
    op.drop_table('call')
    op.drop_table('bookmarkfolder')
    op.drop_table('block')
    op.drop_table('user')
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_phone_number'))

    op.drop_table('otp')
    with op.batch_alter_table('ipinfocache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ipinfocache_ip'))

    op.drop_table('ipinfocache')
    # ### end Alembic commands ###
