"""add_is_superadmin_to_user_and_admin_audit_log

Revision ID: c26c8d0fa2d8
Revises: 86388769acd9
Create Date: 2026-05-10 22:16:10.690217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c26c8d0fa2d8'
down_revision: Union[str, None] = '86388769acd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS adminauditlog (
            id VARCHAR NOT NULL,
            admin_id VARCHAR NOT NULL,
            action VARCHAR NOT NULL,
            target_type VARCHAR,
            target_id VARCHAR,
            meta VARCHAR,
            ip_address VARCHAR,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id),
            FOREIGN KEY (admin_id) REFERENCES "user" (id)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_adminauditlog_admin_id ON adminauditlog (admin_id)")
    op.execute('ALTER TABLE "user" ADD COLUMN IF NOT EXISTS is_superadmin BOOLEAN NOT NULL DEFAULT FALSE')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_superadmin')

    with op.batch_alter_table('adminauditlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adminauditlog_admin_id'))

    op.drop_table('adminauditlog')
    # ### end Alembic commands ###
