"""add disappearing messages timer and expires_at

Revision ID: ca7bc130e901
Revises: fd8c109fc3bb
Create Date: 2026-03-29 03:12:15.463913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca7bc130e901'
down_revision: Union[str, None] = 'fd8c109fc3bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disappearing_timer', sa.Integer(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_message_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_expires_at'))
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('disappearing_timer')

    # ### end Alembic commands ###
