"""add group chat tables and modify chat message for groups

Revision ID: cb1a8f32ab59
Revises: 193fcae71068
Create Date: 2026-03-30 01:00:27.417917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb1a8f32ab59'
down_revision: Union[str, None] = '193fcae71068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatmember',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('added_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatmember', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatmember_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatmember_user_id'), ['user_id'], unique=False)

    op.create_table('senderkey',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chain_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('senderkey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_senderkey_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_senderkey_sender_device_id'), ['sender_device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_senderkey_sender_id'), ['sender_id'], unique=False)

    op.create_table('messagereadreceipt',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messagereadreceipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messagereadreceipt_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messagereadreceipt_user_id'), ['user_id'], unique=False)

    op.create_table('senderkeydistribution',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_chain_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_key_id'], ['senderkey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('senderkeydistribution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_senderkeydistribution_recipient_device_id'), ['recipient_device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_senderkeydistribution_recipient_user_id'), ['recipient_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_senderkeydistribution_sender_key_id'), ['sender_key_id'], unique=False)

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='dm'))
        batch_op.add_column(sa.Column('group_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('group_icon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('group_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('max_members', sa.Integer(), nullable=False, server_default='1024'))
        batch_op.alter_column('participant_one_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('participant_two_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_system_message', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.alter_column('receiver_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('receiver_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('is_system_message')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('participant_two_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('participant_one_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('max_members')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('group_description')
        batch_op.drop_column('group_icon_url')
        batch_op.drop_column('group_name')
        batch_op.drop_column('chat_type')

    with op.batch_alter_table('senderkeydistribution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_senderkeydistribution_sender_key_id'))
        batch_op.drop_index(batch_op.f('ix_senderkeydistribution_recipient_user_id'))
        batch_op.drop_index(batch_op.f('ix_senderkeydistribution_recipient_device_id'))

    op.drop_table('senderkeydistribution')
    with op.batch_alter_table('messagereadreceipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messagereadreceipt_user_id'))
        batch_op.drop_index(batch_op.f('ix_messagereadreceipt_message_id'))

    op.drop_table('messagereadreceipt')
    with op.batch_alter_table('senderkey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_senderkey_sender_id'))
        batch_op.drop_index(batch_op.f('ix_senderkey_sender_device_id'))
        batch_op.drop_index(batch_op.f('ix_senderkey_chat_id'))

    op.drop_table('senderkey')
    with op.batch_alter_table('chatmember', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatmember_user_id'))
        batch_op.drop_index(batch_op.f('ix_chatmember_chat_id'))

    op.drop_table('chatmember')
    # ### end Alembic commands ###
